// Generated by CoffeeScript 1.3.3
(function() {
  var e;

  if (!(typeof jQuery !== "undefined" && jQuery !== null)) {
    e = document.createElement('script');
    e.setAttribute('type', 'text/javascript');
    e.setAttribute('charset', 'UTF-8');
    e.setAttribute('src', '//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js');
    document.body.appendChild(e);
  }

  window.saveTrelloCard = function(idList, key, token) {
    var data = null;  
    var xhr = new XMLHttpRequest();
    xhr.addEventListener("readystatechange", function () {
  if (this.readyState === this.DONE) {
    console.log(this.responseText);
  }
    });
    xhr.open("POST", "https://api.trello.com/5b61a1ff8d7233289bbb1ef0/cards");    
    xhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
    var data1 = {};
    data1.key = "John";
    data1.token  = "Snow";
    data1.name  = document.title;
    data1.desc  = document.location.href;
    data1.idList  = idList;
    var json = JSON.stringify(data1);
    xhr.send(json);
    var json = JSON.parse(xhr.responseText);
    var yourData = json["idList"]
  };

}).call(this);
